---
title: "Micorpattern Images analysis"
output: html_document
date: "2023-01-11"
---
```{r}
.vsc.attach() #attach the environment to VSCode
```
```{r}
library(devtools)
install_github("lldelisle/usefulLDfunctions")
library(usefulLDfunctions)

safelyLoadAPackageInCRANorBioconductor("ggplot2")
safelyLoadAPackageInCRANorBioconductor("ggrepel")
safelyLoadAPackageInCRANorBioconductor("dplyr")
safelyLoadAPackageInCRANorBioconductor("ggpubr")
safelyLoadAPackageInCRANorBioconductor("ggrepel")
safelyLoadAPackageInCRANorBioconductor("Rtsne")
safelyLoadAPackageInCRANorBioconductor("plotly")
safelyLoadAPackageInCRANorBioconductor("limma")
safelyLoadAPackageInCRANorBioconductor("HTqPCR")
safelyLoadAPackageInCRANorBioconductor("readr")
safelyLoadAPackageInCRANorBioconductor("tidyverse")
safelyLoadAPackageInCRANorBioconductor("FactoMineR")
safelyLoadAPackageInCRANorBioconductor("repr")
safelyLoadAPackageInCRANorBioconductor("stringr")
safelyLoadAPackageInCRANorBioconductor("devtools")
safelyLoadAPackageInCRANorBioconductor("factoextra")
#heatmap
safelyLoadAPackageInCRANorBioconductor("heatmaply")
safelyLoadAPackageInCRANorBioconductor("pheatmap")
safelyLoadAPackageInCRANorBioconductor("RColorBrewer")
safelyLoadAPackageInCRANorBioconductor("viridis")


```

# get the data
```{r}
file_list <- c(list.files(
    path = "L:/Pierre/Projects/4-All_git/ScriptsForOsteilEtEl2023/4_Images_Micropattern_analysis/Data/Trial10/", pattern = "*.csv", full.names = TRUE),
    list.files(path = "L:/Pierre/Projects/4-All_git/ScriptsForOsteilEtEl2023/4_Images_Micropattern_analysis/Data/Trial20/", pattern = "*.csv", full.names = TRUE)
)

df_microp <- NULL
for (file in file_list) {
  data <- read.csv(file, sep = ",", header = TRUE)
  data$Sample <- rep(file, length(nrow(data)))
  df_microp <- rbind(df_microp, data)
}
head(df_microp)

rm(data, file_list, file) # clean environment

```

# add some metadata

```{r}
df_microp <- df_microp |> mutate(channel = sapply(str_split(df_microp$Label, "c:|z:| "), `[`, 2))
df_microp <- df_microp |> mutate(Z = sapply(str_split(df_microp$Label, "c:|z:| "), `[`, 4))
df_microp <- df_microp |> mutate(Replicate = sapply(str_split(df_microp$Label, "c:|z:| "), `[`, 9))

df_microp <- df_microp |> mutate(CellLine = sapply(str_split(df_microp$Sample, "0/| "), `[`, 2))
df_microp <- df_microp |> mutate(Genotype = sapply(str_split(df_microp$Sample, " |.csv"), `[`, 2))

df_microp <- df_microp |> mutate(Trial = sapply(str_split(df_microp$Sample, "/"), `[`, 8))

head(df_microp)

```

# Plots
```{r}
toplot <- df_microp |> filter(channel == "3/3") |> filter(!(CellLine  == "MB2")) |> filter(Trial =="Trial20")

# Plot cell density.
Trial10_density<- ggplot(toplot, aes(x = X, y = Y)) +
    geom_hex(stat = "binhex", binwidth = c(50, 50), aes(fill = ..density..)) +
    scale_fill_viridis_c(option = "turbo", trans = "log10") +
    theme_minimal() +
    facet_wrap(CellLine ~ Genotype) +
    coord_fixed()
ggsave("4_Images_Micropattern_analysis/Plots/Trial20_density_plot.pdf", Trial10_density, width = 12, height = 10)

# Create the hexbin-like scatter plot with mean values
FluoPlot <- ggplot(toplot, aes(x = X, y = Y)) +
    geom_hex(binwidth = c(50, 50), aes(fill = ..y..)) +
    facet_wrap(CellLine ~ Genotype)+
    scale_fill_viridis_c(option = "turbo", trans = "log10") +
    stat_summary_hex(
        fun = "mean",
        binwidth = c(50, 50),
        aes(z = Mean),
        show.legend = FALSE
    ) +
  theme_minimal() +
  coord_fixed()
FluoPlot
ggsave("4_Images_Micropattern_analysis/Plots/Trial20_FOXA2_plot.pdf", FluoPlot, width = 12, height = 10)  
```

# Double positive Table
```{r}
df_microp_meta <- cbind.data.frame(df_microp$Label, df_microp$X, df_microp$Y, df_microp$Z, df_microp$CellLine, df_microp$Trial, df_microp$Genotype) 
df_microp_dapi <- df_microp |> filter(channel == "1/3") |> select(Mean)
df_microp_red <- df_microp |> filter(channel == "2/3") |> select(Mean)
df_microp_green <- df_microp |> filter(channel == "3/3") |> select(Mean)

df_microp_dblepos <- cbind.data.frame(df_microp_meta, df_microp_green, df_microp_red, df_microp_dapi)
colnames (df_microp_dblepos) <- c("Label", "X", "Y", "Z", "CellLine", "Trial", "Genotype", "FOXA2", "SOX17", "DAPI")
head(df_microp_dblepos)
rm(df_microp_green, df_microp_red, df_microp_dapi, df_microp_meta)
```

# Double positive Plots
```{r}
tresh_FOXA2 <- 20000 #higher then 3rd Quantile
tresh_SOX17 <- 30000

df_microp_dblepos <- df_microp_dblepos |> mutate(FOXA2single = FOXA2 >= tresh_FOXA2)
df_microp_dblepos <- df_microp_dblepos |> mutate(SOX17single = SOX17 >= tresh_SOX17)
df_microp_dblepos <- df_microp_dblepos |> mutate(DBLE = c(SOX17single + FOXA2single) == 2)

df_microp_dblepos$CellLineGen <- paste0(df_microp_dblepos$CellLine, "_",df_microp_dblepos$Genotype)

#add indices for the top 50000 cells for each cell line
unique(df_microp_dblepos$CellLineGen)
random_1 <- df_microp_dblepos |>
  filter(CellLineGen == "FA3_DO0") |>
  sample_n(100000)
random_2 <- df_microp_dblepos |>
  filter(CellLineGen == "FA3_DO1") |>
  sample_n(100000)
random_3 <- df_microp_dblepos |>
  filter(CellLineGen == "FA3_DO2") |>
  sample_n(100000)

DOX_samples <- rbind.data.frame(random_1, random_2, random_3)

toplot <- DOX_samples |> filter(DBLE == TRUE)
#toplot <- df_microp_dblepos |> filter(DBLE == TRUE) |> filter(!(CellLine  == "MB2")) |> filter(Trial =="Trial20") # nolint

DblePlot <- ggplot(toplot, aes(x = X, y = Y)) +
geom_hex(binwidth = c(50, 50), aes(fill = ..y..)) +
    facet_wrap(CellLine ~ Genotype) +
    scale_fill_viridis_c(option = "turbo", trans = "log10") +
    stat_summary_hex(
        fun = "sum",
        binwidth = c(50, 50),
        aes(z = DBLE),
        show.legend = FALSE
    ) +
  theme_minimal() +
    coord_fixed()
DblePlot
#ggsave("4_Images_Micropattern_analysis/Plots/Trial20_DblePos_plot.pdf", DblePlot, width = 12, height = 10)  

```



```{r}





```