---
title: "R Notebook"
output: html_notebook
---

```{r}
library("ggplot2")
library("ggpubr")
library("tidyverse")
```


```{r}
dat_hep <- read.csv("C:/Users/piosteil/Desktop/Work/3_Australia/hiPSC/hiPSC_paper_V12/Review/data/Results_CellPose.csv", sep = ";")
dim(dat_hep)

summary(dat_hep$Area)
dat_hep <- dat_hep |> filter(Area > pi * 10^2) |>
                mutate(AAT.Norm = AAT.Mean / DAPI.Mean) |>
                mutate(ALB.Norm = ALB.Mean / DAPI.Mean)

head(dat_hep)

ncells <- data.frame(
  CellLine = c("C32", "C11"),
  n = c(nrow(dat_hep |> filter(CellLine == "C32")), 
        nrow(dat_hep |> filter(CellLine == "C11")))
)

FC.alb <- dat_hep |> filter(CellLine == "C32") |> select(ALB.Norm) |> summarise(mean = mean(ALB.Norm)) / 
      dat_hep |> filter(CellLine == "C11") |> select(ALB.Norm) |> summarise(mean = mean(ALB.Norm))
FC.aat <- dat_hep |> filter(CellLine == "C32") |> select(AAT.Norm) |> summarise(mean = mean(AAT.Norm)) / 
      dat_hep |> filter(CellLine == "C11") |> select(AAT.Norm) |> summarise(mean = mean(AAT.Norm))


alb.plot <- ggviolin(dat_hep, x = "CellLine", y = "ALB.Norm", color = "CellLine", add = c("boxplot")) + 
  stat_compare_means(comparisons = list(c("C32", "C11")), method = "t.test") +
  geom_text(data = ncells, aes(x = CellLine, y = 0, label = paste0("n = ", n)), check_overlap = TRUE, vjust = -1)

ggsave("plots/alb.plot.pdf", alb.plot , width = 7, height = 7)


aat.plot <- ggviolin(dat_hep, x = "CellLine", y = "AAT.Norm", color = "CellLine", add = c("boxplot")) + 
  stat_compare_means(comparisons = list(c("C32", "C11")), method = "t.test") +
  geom_text(data = ncells, aes(x = CellLine, y = 0, label = paste0("n = ", n)), check_overlap = TRUE, vjust = -1)
  
ggsave("plots/aat.plot.pdf", aat.plot , width = 7, height = 7)
```

# Cyp Activity
```{r}
# results from Sarah: 

df <- data.frame(
  CellLine = c("C32", "C32", "C11", "C11"),
  Value = c(1966.5, 2985.5, 10485.35277, 16377.9292)
)

# Calculate the SEM
df_sem <- df %>%
  group_by(CellLine) %>%
  summarise(sem = sd(Value) / sqrt(n()))

# Merge the SEM with the original data
df <- df %>%
  left_join(df_sem, by = "CellLine")

level.order <- c("C32", "C11")


cyp.plot <- ggplot(df, aes(x = CellLine, y = Value, fill = CellLine)) +
  geom_bar(stat = "summary", fun.y = "mean") +
  scale_x_discrete(limits = level.order) +
  geom_errorbar(aes(ymin = Value - sem , ymax = Value + sem), width = 0.2) +
  #stat_compare_means(comparisons = list(c("C32", "C11")), method = "t.test") +
  theme_bw()
ggsave("plots/cyp_activity.pdf", cyp.plot, width = 5, height = 7)

```